### ISSUE TITLE
PyPI release  seems to be missing mrmr.cpp

### ISSUE THREAD

**Issue by philtweir** [explosion/murmurhash#10]
At present, I am trying to install spacy via pip. However, it fails on this dependency with:

```
error: murmurhash/mrmr.cpp: No such file or directory
```

The same happens when attempting to install directly. As far as I can tell, this is due to `generate_cython` not being run as `setup.py` recognises it is running in a package, not from source. However, `mrmr.cpp` has not been included in the package.

**Comment by asciiascetic** [comment]
Ah. Nevermind.  For me I just had to `pip install wheel` in my virtual environment.  With `wheel` installed everything else installed as well.

**Comment by honnibal** [comment]
Sorry about this. I've been baffled by this a couple of times as well. I don't understand why pip invokes wheel, and then fails if it's not available??

**Comment by ines** [comment]
We're now shipping pre-built wheels for `murmurhash` and have also added `wheel` to the `setup_requires` for the next release. This should hopefully resolve issues like this!
